### ISSUE TITLE
RC Firmware for Spark

### ISSUE THREAD

**Issue by garonna** [MAVProxyUser/dji_system.bin#22]
Hi,
I would like to load the V01.00.0100_RC_Spark_fw.tar on DroneZbreak to downgrade the RC of my Spark ... but DroneZbreak refused the files .tar or .sig ... what is the trick ? please ?
Thanks

**Comment by kilrah** [comment]
Spark RC firmware flashing doesn't work the same as the rest, dronezbreak doesn't support it AFAIK. Use  pyduml

**Comment by jezzab** [comment]
Spark FW flashing is via WiFi/TCP not FTP. As said, pyduml is the only fw upgrade/downgrade software to support this method at this time.

**Comment by kilrah** [comment]
Dumldore now supporting it
https://github.com/jezzab/DUMLdore/releases/tag/v2.00
