### ISSUE TITLE
binary files can not  be download

### ISSUE THREAD

**Issue by davidtwchn** [MAVProxyUser/dji_system.bin#28]
The binary files can  not be download any more.

**Comment by kilrah** [comment]
What binary files, from where, with what version? Doesn't mean anything...

**Comment by ic0nicinside** [comment]
He's right, none of the firmware can be downloaded from raw.

**Comment by monkey1911** [comment]
I've been trying to download mavic firmware 01.030.0400, 0700 and 01.04.0100 and all I'm getting are 1kb files when I try to download the raw.

**Comment by cs2000** [comment]
GUys, Firmware has been available from alternate sources for a long time. See the link below.

The LFS data has likely been used up.

http://dji.polybotes.feralhosting.com/DJI-Firmware/

**Comment by MAVProxyUser** [comment]
My Git LFS has used full bandwidth for the month, and I am not paying for any more... wait till November 1st and new LFS quota will be available.
