### ISSUE TITLE
Will dropbear patch brick?

### ISSUE THREAD

**Issue by hdnes** [MAVProxyUser/dji_system.bin#7]
Is there a potential to brick if someone put adb persistence somewhere above the patch's edits considering the lines have moved.

**Comment by MAVProxyUser** [comment]
@martinbogo ...

**Comment by martinbogo** [comment]
I do not believe so.  The patch is designed with "if" statements, and designed to go at the very end of the file.  

if the file has been overly modified, the patch will fail, and thus can't brick

**Comment by hdnes** [comment]
Created my own dropbear.sh and tests fine

**Comment by MAVProxyUser** [comment]
attach said script here please?

**Comment by hdnes** [comment]
[dropbear.sh.txt](https://github.com/MAVProxyUser/dji_system.bin/files/1167862/dropbear.sh.txt)
